# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    ENV['CRASHLYTICS_API_TOKEN'] = '16d8061598eb5d06a2ac69a3621537beba88de42'
    ENV['CRASHLYTICS_BUILD_SECRET'] = 'edebe376485cdd09fe7d4eaa78f926b24da6904587718e147fc9a1d7e93f4c41'
    ENV['CRASHLYTICS_FRAMEWORK_PATH'] = './Pods/Crashlytics'
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '120'
    increment_build_number
  end

##################
## Staging lanes
##################

  desc "Send Debug to Fabric"
  lane :fabric_debug do
    gym(
      scheme: "Debug",
      export_method: "development",
      output_directory: "./builds/Debug/",
      clean: true
    )
    crashlytics({
      ipa_path: "./builds/Debug/Dealer App.ipa",
      groups: "jenkins-ios-qa",
      notes: "This app was automatically sent from Fastlane",
      notifications: "true"
    })
  end

  desc "Send Beta to Fabric"
  lane :fabric_beta do
    gym(
      scheme: "Beta",
      export_method: "development",
      output_directory: "./builds/Beta/",
      clean: true
    )
    crashlytics({
      ipa_path: "./builds/Beta/Dealer App.ipa",
      groups: "jenkins-ios-qa",
      notes: "This app was automatically sent from Fastlane",
      notifications: "true"
    })
  end

##################
## Release lanes
##################

  desc "Deploy a new version to the App Store"
  lane :release_on_ci do
    gym(scheme: "Release")
    deliver(force: true)
  end

  desc 'Upload latest dSYMS to Fabric'
  lane :refresh_dsyms do
    download_dsyms(app_identifier: 'ie.distilledsch.Dealer-App', version: 'latest')
    upload_symbols_to_crashlytics
  end

end
